version: '3.8'

  services:
    localstack:
      image: localstack/localstack
      ports:
        - 4567:4566
      options: --health-cmd="curl --silent --fail http://localhost:4566/_localstack/health || exit 1" --health-interval=10s --health-timeout=5s --health-retries=3

  api:
    build:
      context: .
      dockerfile: src/Dockerfile.test
    ports:
      - "5000:5000"
    depends_on:
      - localstack

volumes:
  localstack_volume:
