version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4568:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    healthcheck:
      test: curl --silent --fail http://localhost:4566/_localstack/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      dockerfile: src/Dockerfile.api
    ports:
      - "5002:5000"
    depends_on:
      - localstack

volumes:
  localstack_volume:
